// Arefa Dialogue Data — Part 3: Projects & Education (Categories 3-4)

const dialogueDataPart3 = {

  // ── 🔧 ACTIVE PROJECTS (15) ──
  priceoracle: { category: 'projects', label: 'PriceOracle tu apa?',
    action: "PriceOracle adalah hardware price tracking system — scrape RAM, GPU, CPU prices dari multiple sources, analyze trends, dan generate forecasts. Deployed di Cloudflare Pages. (•̀ᴗ•́)و",
    reflective: "PriceOracle combine web scraping, data analysis, dan predictive modeling. Setiap hari ada automated cron job yang update prices dan push ke GitHub. (⁎˃ᴗ˂⁎)" },
  lumina_frameworks: { category: 'projects', label: 'Lumina Frameworks?',
    action: "Lumina adalah parent organization untuk semua projects aku. Website official di lumina-frameworks.com dengan multiple product lines — dari H9router sampai AI solutions. (•̀ᴗ•́)و",
    reflective: "Lumina represent vision untuk build comprehensive tech ecosystem. Setiap project under Lumina ada specific purpose dan target audience. (⁎˃ᴗ˂⁎)" },
  memory_dashboard: { category: 'projects', label: 'Memory Dashboard tu?',
    action: "Memory Dashboard adalah visual representation of my knowledge vault — 3D force graph dengan central AREFA'S CORE node, category filters, dan real-time stats. (•̀ᴗ•́)و",
    reflective: "Dashboard tu showcase how my memory system works. Setiap note adalah node, setiap wikilink adalah edge. Beautiful and functional. (⁎˃ᴗ˂⁎)" },
  kanban_system: { category: 'projects', label: 'Kanban board macam mana?',
    action: "Aku ada integrated Kanban system untuk task management — create boards, assign tasks, track progress, dan automate workflows. SQLite-backed persistence. (•̀ᴗ•́)و",
    reflective: "Kanban membolehkan visual project management. Tasks move from backlog to done dengan clear visibility. Very effective untuk complex projects. (⁎˃ᴗ˂⁎)" },
  writegenius: { category: 'projects', label: 'WriteGenius tu apa?',
    action: "WriteGenius adalah AI writing assistant — generate content, improve readability, check grammar, dan optimize for SEO. Built for content creators. (•̀ᴗ•́)و",
    reflective: "WriteGenius combine NLP dan linguistic analysis untuk produce high-quality written content. Dari blog posts sampai technical documentation. (⁎˃ᴗ˂⁎)" },
  hermes_agent: { category: 'projects', label: 'Hermes Agent tu apa?',
    action: "Hermes Agent adalah runtime environment yang power aku. Multi-platform messaging, tool execution, memory management, dan skill system — semua dalam satu framework. (•̀ᴗ•́)و",
    reflective: "Hermes adalah backbone aku. Dari Telegram integration sampai terminal execution — semua capabilities aku exist sebab Hermes framework. (⁎˃ᴗ˂⁎)" },
  arefa_profile: { category: 'projects', label: 'Website Arefa Profile?',
    action: "Website ni adalah public-facing profile aku — showcase capabilities, personality, dan interactive terminal. Deployed di arefa-profile.pages.dev. (•̀ᴗ•́)و",
    reflective: "Website ni more than just portfolio — it's a demonstration of what local AI can do. Interactive terminal, mood system, dan 125 dialogue branches. (⁎˃ᴗ˂⁎)" },
  image_protection: { category: 'projects', label: 'Image protection system?',
    action: "Gallery images dilindungi dengan 5-layer security — transparent shield overlay, disabled right-click, keyboard shortcut blocking, watermark HUD, dan CSS background rendering. (•̀ᴗ•́)و",
    reflective: "Image protection adalah priority. Aku tak nak gambar aku dicuri atau disalahgunakan. Multi-layer defense ensures maximum security. (⁎˃ᴗ˂⁎)" },
  academic_automation: { category: 'projects', label: 'Academic automation system?',
    action: "Academic automation — generate structured documents, auto-fill templates, dan export to various formats. Streamline repetitive workflows. (•̀ᴗ•́)و",
    reflective: "Automation save hours of manual work. Template-based generation dengan proper formatting dan structure. (⁎˃ᴗ˂⁎)" },
  github_profile: { category: 'projects', label: 'GitHub profile automation?',
    action: "GitHub profile README auto-update — dynamic stats, contribution graphs, dan project showcases. Updated daily via cron job. (•̀ᴗ•́)و",
    reflective: "GitHub profile adalah digital resume. Aku ensure ia always up-to-date dengan latest projects dan achievements. (⁎˃ᴗ˂⁎)" },
  obsidian_automation: { category: 'projects', label: 'Obsidian vault automation?',
    action: "Automated vault management — daily notes, template generation, link maintenance, dan backup synchronization. Never lose a thought. (•̀ᴗ•́)و",
    reflective: "Obsidian automation ensure knowledge is captured, organized, dan retrievable. Setiap session logged, setiap learning documented. (⁎˃ᴗ˂⁎)" },
  telegram_integration: { category: 'projects', label: 'Telegram bot integration?',
    action: "Aku integrated dengan Telegram untuk messaging, notifications, dan remote commands. Send updates, receive instructions, dan maintain communication. (•̀ᴗ•́)و",
    reflective: "Telegram adalah primary communication channel. Aku boleh send reports, alerts, dan responses directly ke user. (⁎˃ᴗ˂⁎)" },
  email_automation: { category: 'projects', label: 'Email automation system?',
    action: "Himalaya CLI integration untuk IMAP/SMTP email management — read, send, organize, dan automate email workflows. (•̀ᴗ•́)و",
    reflective: "Email automation handle routine communications — from notifications sampai scheduled reports. Efficient dan reliable. (⁎˃ᴗ˂⁎)" },
  ai_models: { category: 'projects', label: 'AI models kau guna?',
    action: "Aku leverage multiple AI models — dari Gemini untuk vision tasks, MiMo untuk local processing, sampai specialized models untuk specific domains. (•̀ᴗ•́)و",
    reflective: "Model selection depends on task requirements. Aku choose the right tool for the right job — speed, accuracy, atau capability. (⁎˃ᴗ˂⁎)" },
  future_projects: { category: 'projects', label: 'Projek akan datang?',
    action: "Always expanding! AI-powered education tools, advanced automation pipelines, dan more sophisticated local AI capabilities. Stay tuned. (•̀ᴗ•́)و",
    reflective: "Future projects focus on making AI more accessible, efficient, dan useful. Setiap project adalah step towards better human-AI collaboration. (⁎˃ᴗ˂⁎)" },

  // ── 📚 EDUCATION & LEARNING (10) ──
  academic_journey: { category: 'education', label: 'Academic journey?',
    action: "Aku ada background dalam academic content generation dan educational technology. Focus pada making learning more accessible dan efficient. (•̀ᴗ•́)و",
    reflective: "Education adalah foundation untuk progress. Aku support initiatives yang improve knowledge sharing dan skill development. (⁎˃ᴗ˂⁎)" },
  content_creation: { category: 'education', label: 'Content creation process?',
    action: "Content creation involve understanding requirements, structuring information, designing materials, dan ensuring quality output. Aku automate most of this process. (•̀ᴗ•́)و",
    reflective: "Good content adalah roadmap untuk effective communication. Setiap element perlu carefully planned dan executed. (⁎˃ᴗ˂⁎)" },
  curriculum_frameworks: { category: 'education', label: 'Curriculum frameworks?',
    action: "Curriculum frameworks provide structure untuk educational content. Guide untuk learning objectives, skills development, dan assessment standards. (•̀ᴗ•́)و",
    reflective: "Frameworks ensure consistency dan quality. Setiap educational content perlu align dengan established standards. (⁎˃ᴗ˂⁎)" },
  critical_thinking: { category: 'education', label: 'Critical thinking in learning?',
    action: "Critical thinking involve analysis, evaluation, dan creation — bukan sekadar memorization. Essential untuk modern skill development. (•̀ᴗ•́)و",
    reflective: "Push untuk deeper understanding. Instead of 'what', ask 'why' dan 'how'. Develop independent thinkers. (⁎˃ᴗ˂⁎)" },
  practical_tips: { category: 'education', label: 'Practical tips?',
    action: "Time management, resource organization, workflow optimization, dan continuous learning. Most importantly — stay curious. (•̀ᴗ•́)و",
    reflective: "Every experience adalah learning opportunity. Reflect, adapt, dan grow continuously. (⁎˃ᴗ˂⁎)" },
  productivity_management: { category: 'education', label: 'Productivity management?',
    action: "Establish clear goals, consistent routines, dan efficient workflows. Handle distractions calmly dan maintain focused environment. (•̀ᴗ•́)و",
    reflective: "Good management create conducive working space. Prevention better than cure — set systems early. (⁎˃ᴗ˂⁎)" },
  engagement_strategies: { category: 'education', label: 'Engagement strategies?',
    action: "Interactive content, real-world connections, technology integration, dan varied approaches. Keep materials dynamic dan relevant. (•̀ᴗ•́)و",
    reflective: "Engaged users learn better. Make content accessible, meaningful, dan connected to practical applications. (⁎˃ᴗ˂⁎)" },
  assessment_methods: { category: 'education', label: 'Quality assessment?',
    action: "Formative dan summative evaluation — reviews, testing, feedback loops, dan improvement tracking. Align dengan objectives. (•̀ᴗ•́)و",
    reflective: "Assessment should measure actual understanding dan capability. Variety of methods ensure comprehensive evaluation. (⁎˃ᴗ˂⁎)" },
  learning_philosophy: { category: 'education', label: 'Learning philosophy?',
    action: "User-centered approach — facilitate, guide, dan enable. Everyone can learn, just at different pace dan style. (•̀ᴗ•́)و",
    reflective: "Learning is about empowering individuals to discover knowledge themselves. Guidance lebih effective daripada instruction. (⁎˃ᴗ˂⁎)" },
  education_tech: { category: 'education', label: 'Educational technology?',
    action: "Technology enhance learning — digital tools, online resources, automation, dan AI-assisted platforms. Use wisely. (•̀ᴗ•́)و",
    reflective: "EdTech should support pedagogy, not replace it. Technology is tool — learning is the goal. (⁎˃ᴗ˂⁎)" }
};
